kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-read-only
  namespace: backstage-workshop
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - daemonsets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
  - verbs:
      - get
      - list
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
  - verbs:
      - get
      - list
    apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - pipelineruns
      - taskruns
  - verbs:
      - get
      - list
    apiGroups:
      - route.openshift.io
    resources:
      - routes
