kind: ConfigMap
apiVersion: v1
metadata:
  name: my-app-config
  namespace: backstage-workshop
data:
  app-config.extra.yaml: >-
    app:
      title: Backstage App
    organization:
      name: Xyz Company
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'docker' # Alternatives - 'local'
      publisher:
        type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API]
      locations:
        - type: url
          target: "https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml"
        - type: url
          target: "https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/remote-templates.yaml"
