kind: ConfigMap
apiVersion: v1
metadata:
  name: my-app-config
  namespace: backstage-workshop
data:
  app-config.extra.yaml: >-
    app:
      baseUrl: "<APPLICATION_HOST_URL>"
      title: Backstage App
    organization:
      name: Xyz Company
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    kubernetes:
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelines'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'
        - group: 'route.openshift.io'
          apiVersion: 'v1'
          plural: 'routes'
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: minikube
              url: ""
              authProvider: 'serviceAccount'
              skipTLSVerify: true
              serviceAccountToken: ""

    backend:
      baseUrl: "<APPLICATION_HOST_URL>"
      listen:
        port: "<PORT>"
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: "<APPLICATION_HOST_URL>"
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: better-sqlite3
        connection: ':memory:'
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'docker' # Alternatives - 'local'
      publisher:
        type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API]
      locations:
        - type: url
          target: "https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml"
        - type: url
          target: "https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/remote-templates.yaml"
